apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxi-outsource-marketplace-stable-drivers-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taxi-outsource-marketplace-stable-drivers-front
  template:
    metadata:
      labels:
        app: taxi-outsource-marketplace-stable-drivers-front
    spec:
      containers:
        - name: taxi-outsource-marketplace-stable-drivers-front
          image: cr.yandex/crpisqmbamdbbsg19jum/drivers-front/production:1.20.0
          env:
            - name: NODE_ENV
              value: "production"
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: '0'
            - name: APP_HOST
              value: "http://172.18.0.18"
            - name: REACT_APP_YA_METRICS_ID
              value: '51653063'
            - name: DETECT_GEOLOCATION
              value: 'true'
          livenessProbe:
            httpGet:
              path: /ping
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /ping
              port: 3000
            failureThreshold: 60
            periodSeconds: 5
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 172.18.0.2
          - 172.17.0.2
          - 172.16.0.2
        searches:
          - auto-internal
