apiVersion: v1
kind: Service
metadata:
  name: taxi-outsource-marketplace-stable-drivers-backoffice-lb
  annotations:
    yandex.cloud/load-balancer-type: internal
    yandex.cloud/subnet-id: b0csl9f1uel7kfbmatnr
spec:
  ports:
    - port: 80
      name: drivers-backoffice-stable
      targetPort: 80
  selector:
    app: taxi-outsource-marketplace-stable-drivers-backoffice
  type: LoadBalancer
