export const USER_GEOLOCATION_REQUESTED = '@@user/USER_GEOLOCATION_REQUESTED';
export const USER_GEOLOCATION_SUCCEEDED = '@@user/USER_GEOLOCATION_SUCCEEDED';
export const USER_GEOLOCATION_FAILED = '@@user/USER_GEOLOCATION_FAILED';

export const SET_ERROR_LOGIN = '@@user/SET_ERROR_LOGIN';
export const SET_ERROR_SMS = '@@user/SET_ERROR_SMS';

export const SET_IS_PROCESSING = '@@user/SET_IS_PROCESSING';

export const LOGIN_SMS_REQUESTED = '@@user/LOGIN_SMS_REQUESTED';
export const LOGIN_SMS_SUCCEEDED = '@@user/LOGIN_SMS_SUCCEEDED';
export const LOGIN_SMS_FAILED = '@@user/LOGIN_SMS_FAILED';

export const LOGIN_REQUESTED = '@@user/LOGIN_REQUESTED';
export const LOGIN_SUCCEEDED = '@@user/LOGIN_SUCCEEDED';
export const LOGIN_FAILED = '@@user/LOGIN_FAILED';

export const RESET = '@@user/RESET';
export const RESET_ERROR = '@@user/RESET_ERROR';

export const LOGOUT_REQUESTED = '@@user/LOGOUT_REQUESTED';
export const LOGOUT_SUCCEEDED = '@@user/LOGOUT_SUCCEEDED';
export const LOGOUT_FAILED = '@@user/LOGOUT_FAILED';

export const USER_INFO_REQUESTED = '@@user/USER_INFO_REQUESTED';
export const USER_INFO_SUCCEEDED = '@@user/USER_INFO_SUCCEEDED';
export const USER_INFO_FAILED = '@@user/USER_INFO_FAILED';

export const SUBSCRIBES_REQUESTED = '@@user/SUBSCRIBES_REQUESTED';
export const SUBSCRIBES_SUCCEEDED = '@@user/SUBSCRIBES_SUCCEEDED';
export const SUBSCRIBES_FAILED = '@@user/SUBSCRIBES_FAILED';

export const FEEDBACK_REQUESTED = '@@user/FEEDBACK_REQUESTED';
export const FEEDBACK_SUCCEEDED = '@@user/FEEDBACK_SUCCEEDED';
export const FEEDBACK_FAILED = '@@user/FEEDBACK_FAILED';

export const TAXIPARK_DRAFT_REQUESTED = '@@user/TAXIPARK_DRAFT_REQUESTED';
export const TAXIPARK_DRAFT_SUCCEEDED = '@@user/TAXIPARK_DRAFT_SUCCEEDED';
export const TAXIPARK_DRAFT_FAILED = '@@user/TAXIPARK_DRAFT_FAILED';
