export const SET_CITY = '@@ui/SET_CITY';
export const SET_IS_MOBILE = '@@ui/SET_IS_MOBILE';

export const OPEN_LOGIN_MODAL = '@@ui/OPEN_LOGIN_MODAL';
export const CLOSE_LOGIN_MODAL = '@@ui/CLOSE_LOGIN_MODAL';

export const OPEN_CITY_MODAL = '@@ui/OPEN_CITY_MODAL';
export const CLOSE_CITY_MODAL = '@@ui/CLOSE_CITY_MODAL';

export const CLICK_CALL_BUTTON = '@@ui/CLICK_CALL_BUTTON';

export const SET_MAP_CENTER = '@@ui/SET_MAP_CENTER';
export const SET_MAP_ZOOM = '@@ui/SET_MAP_ZOOM';

export const CLEAN_SELECTED_OFFERS_POINTS = '@@ui/CLEAN_SELECTED_OFFERS_POINTS';
export const SELECTED_OFFERS_POINTS_ADDED = '@@ui/SELECTED_OFFERS_POINTS_ADDED';

export const SET_FEEDBACK_SUCCESS = '@@ui/SENT_FEEDBACK_SUCCESS';

export const OPEN_DRIVER_CONDITION_MODAL = '@@ui/OPEN_DRIVER_CONDITION_MODAL';
export const CLOSE_DRIVER_CONDITION_MODAL = '@@ui/CLOSE_DRIVER_CONDITION_MODAL';

export const OPEN_DONT_ACCEPT_CALLS_MODAL = '@@ui/OPEN_DONT_ACCEPT_CALLS_MODAL';
export const CLOSE_DONT_ACCEPT_CALLS_MODAL = '@@ui/CLOSE_DONT_ACCEPT_CALLS_MODAL';

export const OPEN_CALL_MODAL = '@@ui/OPEN_CALL_MODAL';
export const CLOSE_CALL_MODAL = '@@ui/CLOSE_CALL_MODAL';

export const OPEN_FEEDBACK_MODAL = '@@ui/OPEN_FEEDBACK_MODAL';
export const CLOSE_FEEDBACK_MODAL = '@@ui/CLOSE_FEEDBACK_MODAL';

export const RESET = '@@user/RESET';

export const SEND_SUBSCRIBE = '@@ui/SEND_SUBSCRIBE';

export const SET_SUBSCRIBE_SUCCESS = '@@ui/SET_SUBSCRIBE_SUCCESS';

export const CLICK_DROP_CALL_BUTTON = '@@ui/CLICK_DROP_CALL_BUTTON';

export const SET_OFFERS_PAGE = '@@ui/SET_OFFERS_PAGE';

export const SET_IS_MAIN_PAGE = '@@ui/SET_IS_MAIN_PAGE';

export const SET_IS_DESKTOP_FILTERS_OPEN = '@ui/SET_IS_DESKTOP_FILTERS_OPEN';
