apiVersion: v1
kind: Service
metadata:
  name: taxi-outsource-marketplace-testing-drivers-backoffice-lb
  annotations:
    yandex.cloud/load-balancer-type: internal
    yandex.cloud/subnet-id: e9btr1pnp13hf98o04rj
spec:
  ports:
    - port: 80
      name: drivers-backoffice
      targetPort: 80
  selector:
    app: taxi-outsource-marketplace-testing-drivers-backoffice
  type: LoadBalancer
