apiVersion: v1
kind: Service
metadata:
  name: taxi-outsource-marketplace-testing-drivers-front-lb
  annotations:
    yandex.cloud/load-balancer-type: internal
    yandex.cloud/subnet-id: b0cuobd1d43hshrn5h7r
spec:
  ports:
    - port: 80
      name: front
      targetPort: 80
  selector:
    app: taxi-outsource-marketplace-testing-drivers-front
  type: LoadBalancer
