apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxi-outsource-marketplace-testing-drivers-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taxi-outsource-marketplace-testing-drivers-front
  template:
    metadata:
      labels:
        app: taxi-outsource-marketplace-testing-drivers-front
    spec:
      containers:
        - name: taxi-outsource-marketplace-testing-drivers-front
          image: cr.yandex/crpve1keoaktj3501nil/drivers-front:1.20.0
          env:
            - name: YANDEX_ENVIRONMENT
              value: "testing"
            - name: APP_HOST
              value: "http://172.16.0.16"
            - name: REACT_APP_YA_LINK_TAXIPARK_LOGIN
              value: "https://taximeter-client.taxi.tst.yandex.ru/marketplace"
            - name: DETECT_GEOLOCATION
              value: "true"
            - name: REACT_APP_YA_METRICS_ID
              value: "51653063"
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
          livenessProbe:
            httpGet:
              path: /ping
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /ping
              port: 3000
            failureThreshold: 60
            periodSeconds: 5
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 172.18.0.2
          - 172.17.0.2
          - 172.16.0.2
        searches:
          - auto-internal
